[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/auth/*"
  to = "https://dev.apinetbo.bekindnetwork.com/api/Authentication/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/actions*"
  to = "https://dev.api.bekindnetwork.com/api/v1/actions:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
